//! This module defines the `Commands` enum, which represents a set of commands for
//! communicating with the RoboClaw motor controller. Each command corresponds to a specific
//! action or query, such as motor control, encoder reading, voltage settings, and configuration
//! management. The commands are encoded as `u8` values for efficient transmission over a serial
//! communication protocol.
//!
//! These commands are used internally to send instructions to the RoboClaw controller, and each
//! variant in the `Commands` enum maps to a specific function or operation of the controller.

#[allow(dead_code)]
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Commands {
    M1Forward = 0,
    M1Backward = 1,
    SetMinMainVoltage = 2,
    SetMaxMainVoltage = 3,
    M2Forward = 4,
    M2Backward = 5,
    M1Drive = 6,
    M2Drive = 7,
    MixDriveForward = 8,
    MixDriveBackward = 9,
    MixTurnRight = 10,
    MixTurnLeft = 11,
    MixDrive = 12,
    TurnLeftRight = 13,
    SetSerialTimeout = 14,
    ReadSerialTimeout = 15,
    M1ReadEncoder = 16,
    M2ReadEncoder = 17,
    M1ReadSpeedCPS = 18,
    M2ReadSpeedCPS = 19,
    ResetEncoders = 20,
    ReadFirmwareVersion = 21,
    M1SetEncoder = 22,
    M2SetEncoder = 23,
    ReadMainBatVoltage = 24,
    ReadLogicBatVoltage = 25,
    SetMinLogicVoltage = 26,
    SetMaxLogicVoltage = 27,
    M1SetVelocityPIDConst = 28,
    M2SetVelocityPIDConst = 29,
    M1ReadRawSpeed = 30,
    M2ReadRawSpeed = 31,
    M1DriveSignedDutyCycle = 32,
    M2DriveSignedDutyCycle = 33,
    MixDriveSignedDutyCycle = 34,
    M1DriveSignedSpeed = 35,
    M2DriveSignedSpeed = 36,
    MixDriveSignedSpeed = 37,
    M1DriveSignedSpeedAccel = 38,
    M2DriveSignedSpeedAccel = 39,
    MixDriveSignedSpeedAccel = 40,
    M1DriveSignedSpeedDistanceBuffered = 41,
    M2DriveSignedSpeedDistanceBuffered = 42,
    MixDriveSignedSpeedDistanceBuffered = 43,
    M1DriveSignedSpeedAccelDistanceBuffered = 44,
    M2DriveSignedSpeedAccelDistanceBuffered = 45,
    MixDriveSignedSpeedAccelDistanceBuffered = 46,
    ReadBufferLength = 47,
    ReadMotorPWMs = 48,
    ReadMotorCurrents = 49,
    MixDriveIndividualSignedSpeedAccel = 50,
    MixDriveIndividualSignedSpeedAccelDistance = 51,
    M1DriveSignedDutyAccel = 52,
    M2DriveSignedDutyAccel = 53,
    MixDriveSignedDutyAccel = 54,
    M1ReadVelocityPIDConsts = 55,
    M2ReadVelocityPIDConsts = 56,
    SetMainBatVoltage = 57,
    SetLogicBatVoltage = 58,
    ReadMainBatVoltageSettings = 59,
    ReadLogicBatVoltageSettings = 60,
    M1SetPositionPIDConsts = 61,
    M2SetPositionPIDConsts = 62,
    M1ReadPositionPIDConsts = 63,
    M2ReadPositionPIDConsts = 64,
    M1DriveSpeedAccelDeccelPosition = 65,
    M2DriveSpeedAccelDeccelPosition = 66,
    MixDriveSpeedAccelDeccelPosition = 67,
    M1SetDefaultDutyCycle = 68,
    M2SetDefaultDutyCycle = 69,
    M1SetDefaultSpeed = 70,
    M2SetDefaultSpeed = 71,
    ReadDefaultSpeedSettings = 72,

    SetS3S4S5Modes = 74,
    ReadS3S4S5Modes = 75,
    SetDeadBandRCAnalog = 76,
    ReadDeadBandRCAnalog = 77,
    ReadEncoderCounts = 78,
    ReadRawMotorSpeeds = 79,
    RestoreDefaults = 80,
    ReadDefaultDutyCycleAccel = 81,
    ReadTemperature1 = 82,
    ReadTemperature2 = 83,

    ReadStatus = 90,
    ReadEncoderModes = 91,
    M1SetEncoderMode = 92,
    M2SetEncoderMode = 93,
    EEPROMWriteSettings = 94,
    EEPROMReadSettings = 95,

    SetStandardConfigSettings = 98,
    ReadStandardConfigSettings = 99,
    SetCTRLModes = 100,
    ReadCTRLModes = 101,
    SetCTRL1 = 102,
    SetCTRL2 = 103,
    ReadCTRLs = 104,
    M1SetAutoHomeDutySpeedTimeout = 105,
    M2SetAutoHomeDutySpeedTimeout = 106,
    ReadAutoHomeSettings = 107,
    ReadMotorAvgSpeed = 108,
    SetSpeedErrorLimits = 109,
    ReadSpeedErrorLimits = 110,
    ReadSpeedErrors = 111,
    SetPositionErrorLimits = 112,
    ReadPositionErrorLimits = 113,
    ReadPositionErrors = 114,
    SetBatteryVoltageOffsets = 115,
    ReadBatteryVoltageOffsets = 116,
    SetCurrentBlankingPercentages = 117,
    ReadCurrentBlankinPercentages = 118,
    M1DrivePosition = 119,
    M2DrivePosition = 120,
    MixDrivePosition = 121,
    M1DriveSpeedPosition = 122,
    M2DriveSpeedPosition = 123,
    MixDriveSpeedPosition = 124,

    M1SetMaxCurrent = 133,
    M2SetMaxCurrent = 134,
    M1ReadMaxCurrent = 135,
    M2ReadMaxCurrent = 136,

    SetPWMMode = 148,
    ReadPWMMode = 149,

    EEPROMReadUserMemoryLocation = 252,
    EEPROMWriteUserMemoryLocation = 253,
}